### ISSUE TITLE
new feature: Compatibility for 7.40

### ISSUE THREAD

**Issue by Alih-b** [Marc-Bernard-Tools/MBT-Package-Manager#81]
### Version

Version: 1.4.1

### Description of the Feature Request

Hi Mark,

First, I would like to say that this is a great tool! It really helps to boost productivity while working with SAP GUI...
I tried to install the installer, package manager, and Command-Field tool on SAP BASIS 7.40 (On-premises).
The installer took a while to compile and had no problem. However, the package manager and command-field tool encountered an issue because **CL_ABAP_CONV_CODEPAGE** didn't exist on the system.
To fix that, I implemented that class on the system as a customer production program and modified the code to use the new class instead. Luckily it was not a complex class and didn't require much effort and many of its methods were not needed for this tool to work.
I can use command field successfully now; some features don't work but in overall it is working well.

I would like to know how I could contribute to the project, regarding compatibility and maybe adding new features...

Cheers and keep up the good work!

### Additional Information

![image](https://github.com/Marc-Bernard-Tools/MBT-Command-Field/assets/65496394/0779866f-5300-4de5-a50f-3b134edf7504)

**Comment by mbtools** [comment]
I published release 1.4.5. Please give it a try 😃
