### ISSUE TITLE
Bug: Non-existing parameter in calling BAL_LOG_MSG_ADD_FREE_TEXT

### ISSUE THREAD

**Issue by Alih-b** [Marc-Bernard-Tools/MBT-Package-Manager#87]
### Version

Version: 1.4.4

### Description of the Bug

<img width="369" alt="bug" src="https://github.com/Marc-Bernard-Tools/MBT-Package-Manager/assets/65496394/39a3a7c0-35c5-4b87-8265-b16b4380f16f">

![image](https://github.com/Marc-Bernard-Tools/MBT-Package-Manager/assets/65496394/edfaa8f8-dd25-4310-bb02-2555dfca0422)

### Steps To Reproduce

1. import package manager
2. try to activate it

**Comment by mbtools** [comment]
Parameter `i_detlevel` already exists in 7.02 (SP 21). Which release / sp do you have?

**Comment by mbtools** [comment]
Closed by #89
